language: go
go_import_path: github.com/home-assistant/hassio-cli
matrix:
  fast_finish: true
  include:
  - go: 1.x
  - go: '1.6'
  - go: '1.6'
    env: LINT=True
    install: go get -u github.com/golang/lint/golint
    language: bash
    script: golint -set_exit_status
  - go: 1.7.x
  - go: 1.7.x
    env: DEPLOY:True
    addons:
      apt:
        packages: 
          - golang-go-linux-arm
          - upx
    before_deploy:
    - gox -osarch="linux/amd64 linux/arm linux/arm64" -ldflags="-s -w" -output="hassiocli_{{.Arch}}"
    - go build -ldflags="-s -w" -o "hassiocli_x64"
    - GOARCH=arm go build -ldflags="-s -w" -o "hassiocli_arm"
    - GOARCH=arm64 go build -ldflags="-s -w" -o "hassiocli_arm64"
    - upx --brute hassiocli*
    deploy:
      provider: releases
      github_token: $github_token
      file_glob: true
      file: hassiocli*
      skip_cleanup: true
  - go: master
